[pytest]
minversion = "9.0" # config in toml only since v9.0.0
addopts = [
    "--verbose",
]
# https://pytest-asyncio.readthedocs.io/en/latest/reference/configuration.html#asyncio-default-fixture-loop-scope
asyncio_default_fixture_loop_scope = "function"
