line-length = 79
target-version="py311"
src = ["src"]

include = ["src/**.py", "tests/**.py"]
exclude = ["src/dishka/_adaptix/**"]

lint.select = [
    "ALL"
]
lint.ignore = [
    "ARG",
    "ANN",
    "D",
    "EM101",
    "EM102",
    "PT001",
    "PT023",
    "SIM108",
    "RET505",
    "PLR0913",
    "SIM103",
    "ISC003",
    "PGH005", # false positive on requests_mock
    "PERF401",  # incorrect perf suggestion

    # identical by code != identical by meaning
    "SIM114",

    # awful things, never use.
    # It makes runtime work differently from typechecker
    "TC001",
    "TC002",
    "TC003",
    "TC006",
]

[lint.per-file-ignores]
"tests/**" = ["TID252", "PLR2004", "S101", "A002"]

[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
